# Generated by Django 5.2.5 on 2026-07-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_team_options_remove_team_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchprediction',
            name='gameweek',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='kickoff_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='match_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='venue',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
