# Generated by Django 5.2.5 on 2026-08-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_matchprediction_gameweek_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='stadium_name',
            field=models.CharField(default='Main Stadium', max_length=150),
        ),
        migrations.AlterField(
            model_name='matchprediction',
            name='gameweek',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='matchprediction',
            unique_together={('home_team', 'away_team')},
        ),
    ]
