# Generated by Django 5.2.5 on 2026-08-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_team_logo_url_team_stadium_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchprediction',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='team',
            name='stadium_name',
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='away_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='home_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchprediction',
            name='gameweek',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='matchprediction',
            name='prediction',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('D', 'Draw'), ('A', 'Away')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='matchprediction',
            name='kickoff_time',
        ),
        migrations.RemoveField(
            model_name='matchprediction',
            name='match_date',
        ),
        migrations.RemoveField(
            model_name='matchprediction',
            name='venue',
        ),
    ]
