# Generated by Django 5.2.5 on 2026-08-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_matchcommentary_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchprediction',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
