# Generated by Django 5.2.5 on 2026-08-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_matchprediction_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchprediction',
            name='minute',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
