# Generated by Django 5.2.5 on 2026-08-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_matchprediction_minute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchprediction',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='is_scored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
